### ISSUE TITLE
Error in `EXTRA_GDS_FILES`

### ISSUE THREAD

**Issue by kareefardi** [efabless/openlane2#157]
The flow generated the following error, with a configuration that uses `EXTRA_GDS_FILES`:

```
Read error on file: /home/karim/work/caravel_user_project/openlane/user_project_wrapper/runs/RUN_2023-08-23_00-04-30/32-odb-reportwirelength
(errno=21) in Layout.read
[00:06:46] ❌  Read error on file:                                                                                                    step.py:887
           /home/karim/work/caravel_user_project/openlane/user_project_wrapper/runs/RUN_2023-08-23_00-04-30/32-odb-reportwirelength
           (errno=21) in Layout.read

           ❌  Log file:                                                                                                              step.py:888
           '../caravel_user_project/openlane/user_project_wrapper/runs/RUN_2023-08-23_00-04-30/39-klayout-streamout/klayout-streamout
           .log'
           ❌  The following error was encountered while running the flow: GDSII Stream Out (KLayout): subprocess (1,             __main__.py:138
           ['/nix/store/65cp4izx3bllnwqn7c7dhrq9h9gmjkal-python3-3.10.9/bin/python3.10',
           '/nix/store/ixgj4fj9c5bfj4vyzr27gqdzck762rmc-python3.10-openlane/lib/python3.10/site-packages/openlane/scripts/klayout
           /stream_out.py',
           '/home/karim/work/caravel_user_project/openlane/user_project_wrapper/runs/RUN_2023-08-23_00-04-30/32-odb-reportwirelen
           gth/user_project_wrapper.def', '--output',
           '/home/karim/work/caravel_user_project/openlane/user_project_wrapper/runs/RUN_2023-08-23_00-04-30/39-klayout-streamout
           /user_project_wrapper.klayout.gds', '--lyt', '/home/karim/work/pdk/sky130A/libs.tech/klayout/tech/sky130A.lyt',
           '--lyp', '/home/karim/work/pdk/sky130A/libs.tech/klayout/tech/sky130A.lyp', '--lym',
           '/home/karim/work/pdk/sky130A/libs.tech/klayout/tech/sky130A.map', '--top', 'user_project_wrapper', '--input-lef',
           '/home/karim/work/pdk/sky130A/libs.ref/sky130_fd_sc_hd/techlef/sky130_fd_sc_hd__nom.tlef', '--input-lef',
           '/home/karim/work/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lef/sky130_fd_sc_hd.lef', '--input-lef',
           '/home/karim/work/pdk/sky130A/libs.ref/sky130_fd_sc_hd/lef/sky130_ef_sc_hd.lef', '--input-lef', '', '--input-lef',
           '/home/karim/work/caravel_user_project/lef/user_proj_example.lef', '--with-gds-file',
           '/home/karim/work/pdk/sky130A/libs.ref/sky130_fd_sc_hd/gds/sky130_fd_sc_hd.gds', '--with-gds-file', '',
           '--with-gds-file', '/home/karim/work/caravel_user_project/gds/user_proj_example.gds']) failed
``` 
I noticed this in `resolved.json`: 

```
    "MACROS": {
        "user_proj_example": {
            "gds": [
                ""
            ],
            "lef": [
                ""
            ],
            "instances": {},
            "nl": [],
            "spef": {
                "min_*": [
                    "/home/karim/work/caravel_user_project/spef/multicorner/user_proj_example.min.spef"
                ],
                "nom_*": [
                    "/home/karim/work/caravel_user_project/spef/multicorner/user_proj_example.nom.spef"
                ],
                "max_*": [
                    "/home/karim/work/caravel_user_project/spef/multicorner/user_proj_example.max.spef"
                ]
            },
            "lib": {},
            "spice": [],
            "sdf": {},
            "json_h": null
        }
    },
```
While `EXTRA_GDS_FILES` remains like this:

```
    "EXTRA_GDS_FILES": [
        "/home/karim/work/caravel_user_project/gds/user_proj_example.gds"
    ],
```

Furthermore, attempts to create a reproducible results in the following error:

```
[nix-shell:~/work/openlane2]$ python3 -m openlane.steps create-reproducible -d /home/karim/work/caravel_user_project/openlane/user_project_wrapper/runs/RUN_2023-08-23_00-04-30/32-odb-reportwirelength
Traceback (most recent call last):
  File "/nix/store/65cp4izx3bllnwqn7c7dhrq9h9gmjkal-python3-3.10.9/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/nix/store/65cp4izx3bllnwqn7c7dhrq9h9gmjkal-python3-3.10.9/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/karim/work/openlane2/openlane/steps/__main__.py", line 386, in <module>
    cli()
  File "/nix/store/ns7p6q9gw667v41ysn750103v7dgxgwz-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/nix/store/ns7p6q9gw667v41ysn750103v7dgxgwz-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/nix/store/ns7p6q9gw667v41ysn750103v7dgxgwz-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/nix/store/ns7p6q9gw667v41ysn750103v7dgxgwz-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/nix/store/ns7p6q9gw667v41ysn750103v7dgxgwz-python3.10-click-8.1.3/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/nix/store/ns7p6q9gw667v41ysn750103v7dgxgwz-python3.10-click-8.1.3/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/karim/work/openlane2/openlane/steps/__main__.py", line 368, in create_reproducible
    step = load_step_from_inputs(ctx, id, config, state_in)
  File "/home/karim/work/openlane2/openlane/steps/__main__.py", line 67, in load_step_from_inputs
    return Target.load(
  File "/home/karim/work/openlane2/openlane/steps/step.py", line 491, in load
    config, _ = Config.load(
  File "/home/karim/work/openlane2/openlane/config/config.py", line 435, in load
    loaded = loader(
  File "/home/karim/work/openlane2/openlane/config/config.py", line 596, in __load_dict
    raise InvalidConfig(
openlane.config.config.InvalidConfig: The following errors were encountered:
	* Path provided for variable 'MACROS.user_proj_example.gds[0]' does not exist: ''
```

To reproduce:

Relevant `config.json`, repo and branch: https://github.com/efabless/caravel_user_project/blob/openlane2-support/openlane/user_project_wrapper/config.json

**Comment by donn** [comment]
Fixed in #159
